#!/bin/bash

set -e

CONFIG="$PWD/config"
MODULES="$PWD/modules"

function link() {
  local source=$1
  local target=$2

  echo "Checking '${source}'..."
  if [ ! -L ${target} ]; then
    echo "=> Linking '${source}' to '${target}'..."
    ln -s ${source} ${target}
  fi
}

link $CONFIG/starship/starship.toml $HOME/.config/starship.toml
link $CONFIG/zsh/zshrc.zsh $HOME/.zshrc
link $CONFIG/zsh $HOME/.config/zsh
link $MODULES/zgen $HOME/.zgen
link $CONFIG/fish $HOME/.config/fish
link $CONFIG/htop $HOME/.config/htop
link $MODULES/nvchad $HOME/.config/nvim
link $CONFIG/nvim/custom $HOME/.config/nvim/lua/custom
link $CONFIG/tmux $HOME/.config/tmux
link $CONFIG/iterm2 $HOME/.config/iterm2
