#!/bin/bash

set -e

CONFIG="install.conf.yaml"
DOTBOT_DIR="modules/dotbot"

DOTBOT_BIN="bin/dotbot"
BASEDIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

cd "${BASEDIR}"
git -C "${DOTBOT_DIR}" submodule sync --quiet --recursive
git submodule update --init --recursive "${DOTBOT_DIR}"

"${BASEDIR}/${DOTBOT_DIR}/${DOTBOT_BIN}" \
  -d "${BASEDIR}" \
  --plugin-dir "${BASEDIR}/modules/dotbot-brewfile" \
  --plugin-dir "${BASEDIR}/modules/dotbot-asdf" \
  -c "${CONFIG}" "${@}"
