#!/usr/bin/env bash

set -e

DEFAULT_CONFIG="install.conf.yaml"
DOTBOT_DIR="modules/dotbot"
DOTBOT_BIN="bin/dotbot"
BASEDIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

if [ $# -eq 0 ]; then
  echo "Usage: ./install <profile>"
  echo "Profiles: personal  work  linux"
  exit 1
fi

cd "${BASEDIR}"
git -C "${DOTBOT_DIR}" submodule sync --quiet --recursive
git submodule update --init --recursive "${DOTBOT_DIR}"

for conf in "${DEFAULT_CONFIG}" "${@/%/.conf.yaml}"; do
  "${BASEDIR}/${DOTBOT_DIR}/${DOTBOT_BIN}" -d "${BASEDIR}" -c "${conf}"
done
