"$schema" = 'https://starship.rs/config-schema.json'

format = """
$directory\
$git_branch\
$git_status\
$character\
"""
right_format = """$shell$cmd_duration"""

add_newline = false

[directory]
truncation_length = 7
truncate_to_repo = false
truncation_symbol = '…/'
style = 'bold fg:39'
repo_root_style = 'bold fg:31'
before_repo_root_style = 'bold fg:39'

[git_branch]
format = '[$branch(:$remote_branch)]($style)'
style = 'bold fg:76'

[git_status]
format = '([\[$all_status$ahead_behind\]]($style))'
ahead = '⇡$count'
diverged = '⇕⇡$ahead_count⇣$behind_count'
behind = '⇣$count'

[rust]
format = '[$symbol($version )]($style)'

[cmd_duration]
min_time = 500
format = ' [$duration]($style)'
