"$schema" = 'https://starship.rs/config-schema.json'

# format = '$directory$character'
format = """
$shell\
$directory\
$git_branch\
$git_status\
$java\
$rust\
$cmd_duration\
$character\
"""

# Disable the blank line at the start of the prompt
add_newline = false

[directory]
truncation_length = 7
truncate_to_repo = false
truncation_symbol = '…/'
style = 'bold fg:39'
repo_root_style = 'bold fg:31'
before_repo_root_style = 'bold fg:39'

[git_branch]
format = '[$symbol$branch(:$remote_branch)]($style) '
style = 'bold fg:76'

[git_status]
ahead = '⇡$count'
diverged = '⇕⇡$ahead_count⇣$behind_count'
behind = '⇣$count'

[java]
format = '[$symbol($version )]($style)'
version_format = '$raw'

[rust]
format = '[$symbol($version )]($style)'

[cmd_duration]
min_time = 500
format = 'took [$duration]($style) '

[shell]
disabled = false
style = 'cyan bold'
format = '\[[$indicator]($style)\]:'
