name: Update Submodules
on:
  schedule:
    - cron:  '0 0 * * *'    # once a day at midnight
jobs:
  steps:
  - name: Checkout repository
    uses: actions/checkout@v2
  - name: Checkout submodules
    run: git submodule update --init --recursive
