name: Update Submodules
on:
  schedule:
    - cron:  '0 0 * * *'    # once a day at midnight
jobs:
  update_submodules:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Pull & update submodules recursively
        run: |
          git submodule update --init --recursive
          git submodule update --recursive --remote
      - name: Commit
        run: |
          git config user.email ${{ secrets.USER_EMAIL }}
          git config user.name ${{ secrets.USER_NAME }}
          git add --all
          git commit -m "chore(modules): update submodules" || echo "No changes to commit"
          git push
